# Generated by Django 2.1.7 on 2019-02-26 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('amount', models.IntegerField()),
                ('measurement', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Recipee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('cooking_instructions', models.TextField()),
                ('slug', models.SlugField()),
                ('preparation_time', models.IntegerField(help_text='Preparation time in minutes')),
                ('cooking_time', models.IntegerField(help_text='Cooking time in minutes')),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='p3erest.Recipee'),
        ),
    ]
